---
name: 'Deploy Helm'
description: 'Deploy an application version to a given environment'
inputs:
  chart:
    description: Chart name
  release:
    description: Release name
    required: true
  action:
    description: "Operation to execute (install, uninstall, status)"
    default: "install"
  namespace:
    description: Namespace
    default: "default"
  version:
    description: Chart version
  value-file:
    description: Additional value file
  inline-value-file:
    description: Additional value file
  extra-vars:
    description: Additional variables
  repository:
    description: "HTTP or OCI Helm repository for charts (mutually exclusive with chart-path)"
    default: ""
  chart-path:
    description: "Chart directory for local installation (mutually exclusive with repository)"
  repository-username:
    description: Helm repository username
  repository-password:
    description: Helm repository password
  values:
    description: Values in JSON format
  dry-run:
    description: Dry Run
    default: "false"
  wait:
    description: Wait until deployment is successful
    default: "true"
  timeout:
    description: Duration to wait for Kubernetes commands to complete
    default: "10m0s"
  rollback-on-failure:
    description: Rollback install if the upgrade fails
    default: "false"
outputs:
  status:
    description: "Status"
  revision:
    description: "Revision"
  first-deployed:
    description: "Date of the first deployment"
  last-deployed:
    description: "Date of the last deployment"
runs:
  using: 'node20'
  main: 'dist/index.js'
