---
name: dtrack-sbom-gradle
description: 'Build SBOM and upload it in dependency track for gradle projects'

inputs:
  serverHostname:
    description: 'Dependency track server hostname'
    required: true
  serverPort:
    description: 'Dependency track server port (Default is 443)'
    required: false
    default: '443'
  serverProtocol:
    description: 'Dependency track server protocol (Can be https or http, default is https)'
    required: false
    default: 'https'
  apiKey:
    description: 'Dependency track API key'
    required: true
  parentName:
    description: 'Parent project name in Dependency track (Parent version is also required)'
    required: false
    default: ''
  parentVersion:
    description: 'Parent project version in Dependency track (Parent name is also required)'
    required: false
    default: ''
  version:
    description: 'A string value that will be set as version to dependency track'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Build SBOM
      shell: bash
      run: ./gradlew --init-script cyclonedx.gradle cyclonedxBom

    - name: Discover project variables
      shell: bash
      id: vars
      run: |
        echo "PROJECT_NAME=$(./gradlew properties --no-daemon --console=plain -q | grep "^Root project" | awk '{printf $3}' | sed "s/'//g")" >> $GITHUB_OUTPUT

    - name: Upload to dependency track
      id: upload-to-dependency-track
      uses: DependencyTrack/gh-upload-sbom@v3.0.0
      with:
        serverHostname: ${{ inputs.serverHostname }}
        apiKey: ${{ inputs.apiKey }}
        protocol: ${{ inputs.serverProtocol }}
        port: ${{ inputs.serverPort }}
        projectName: ${{ steps.vars.outputs.PROJECT_NAME }}
        projectVersion: ${{ inputs.version }}
        bomFilename: 'build/reports/sbom.json'
        autoCreate: true
        parentName: ${{ inputs.parentName }}
        parentVersion: ${{ inputs.parentVersion }}
