---
name: Chart watcher
on:
  push:
    branches:
      - main
    paths:
      - '**/action.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # We use this token to be able to change workflows from a workflow
        with:
          token: ${{ secrets.WATCHER_PAT_TOKEN }}

      - name: generate and commit the deploy workflows
        working-directory: ./ci
        run: ./create_workflows.sh
